- name: Enable and start NetworkManager service
  systemd:
    name: NetworkManager
    enabled: yes
    state: started

- name: Ensure interfaces are managed by NetworkManager
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    regexp: '^managed='
    line: 'managed=true'
    insertafter: '^\[ifupdown\]'
    backup: yes

- name: Create and activate connection for enp1s0
  shell: |
    nmcli connection add type ethernet ifname enp1s0 con-name eth0 autoconnect yes
    nmcli connection up eth0
  args:
    creates: /etc/NetworkManager/system-connections/eth0.nmconnection

- name: Restart NetworkManager to apply config changes
  systemd:
    name: NetworkManager
    state: restarted
