- name: Enable and start NetworkManager service
  systemd:
    name: NetworkManager
    enabled: yes
    state: started

- name: Set NetworkManager as netplan renderer
  template:
    src: 01-network-manager.yaml.j2
    dest: /etc/netplan/01-network-manager.yml

- name: Create a static ethernet connection using nmcli
  community.general.nmcli:
    conn_name: static-ip
    type: ethernet
    ifname: enp1s0
    ip4: "{{ static_ip }}"
    gw4: "{{ gateway_ip }}"
    dns4:
      - "{{ dns1 }}"
      - "{{ dns2 }}"
    state: present
    autoconnect: yes

- name: Apply netplan configuration
  command: netplan apply
  notify: Restart NetworkManager
