- name: Enable and start NetworkManager service
  systemd:
    name: NetworkManager
    enabled: yes
    state: started

- name: Set NetworkManager as netplan renderer
  template:
    src: 01-network-manager.yml.j2
    dest: /etc/netplan/01-network-manager.yml

- name: Apply netplan configuration
  command: netplan apply
  notify: Restart NetowrkManager

- name: Add static IP connection
  command: >
    nmcli connection add type ethernet ifname {{ interface_name }}
    con-name {{ connection_name }}
    ip4 {{ static_ip }}
    gw4 {{ gateway_ip }}
    ipv4.dns "{{ dns_servers }}"
    ipv4.method manual
  args:
    creates: "/etc/NetworkManager/system-connections/{{ connection_name }}.nmconnection"

- name: Bring up the connection
  command: nmcli connection up {{ connection_name }}
