- name: Enable and start NetworkManager service
  systemd:
    name: NetworkManager
    enabled: yes
    state: started

- name: Ensure interfaces are managed by NetworkManager
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    regexp: '^managed='
    line: 'managed=true'
    insertafter: '^\[ifupdown\]'
    backup: yes

- name: Comment out static enp1s0 config
  replace:
    path: /etc/network/interfaces
    regexp: '^(.*enp1s0.*)$'
    replace: '# \1'
  notify: Restart networking

- name: Restart NetworkManager to apply config changes
  systemd:
    name: NetworkManager
    state: restarted
