- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt: 
    upgrade: dist

- name: Install application list
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ app_list }}"
